config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :product_categories
  root 'home#index'

  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :sku, presence: true, uniqueness: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
    has_many :products, dependent: :destroy
    validates :name, presence: true
    validates :sku, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
    def index
      @product_categories = ProductCategory.all
    end
  
    def show
      @product_category = ProductCategory.find(params[:id])
    end
  
    def new
      @product_category = ProductCategory.new
    end
  
    def create
      @product_category = ProductCategory.new(product_category_params)
        if @product_category.save
          redirect_to product_category_url(@product_category), notice: "Category was successfully created." 
        else
         render :new, status: :unprocessable_entity
        end
    end
  
    def edit
      @product_category = ProductCategory.find(params[:id])
    end
  
    def update
      @product_category = ProductCategory.find(params[:id])
        if @product_category.update(product_category_params)
          redirect_to product_category_url(@product_category), notice: "Category was successfully updated." 
        else
          render :edit, status: :unprocessable_entity 
        end
    end
  
    def destroy 
      @product_category = ProductCategory.find(params[:id])
      @product_category.destroy 
      redirect_to product_categories_path, notice: "Category was successfully deleted." 
    end
    
    private
  
    def product_category_params
      params.require(:product_category).permit(:sku, :name, :description)
    end

  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
      if @product.save
        redirect_to product_url(@product), notice: "Product was successfully created." 
      else
       render :new, status: :unprocessable_entity
      end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
      if @product.update(product_params)
        redirect_to product_url(@product), notice: "Product was successfully updated." 
      else
        render :edit, status: :unprocessable_entity 
      end
  end

  def destroy 
    @product = Product.find(params[:id])
    @product.destroy 
    redirect_to products_path, notice: "Product was successfully deleted." 
  end
  
  private

  def product_params
    params.require(:product).permit(:sku, :name, :description, :product_category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
  <%= render 'shared/alerts' %>

    <%= yield %>
  </body>
</html>

app/views/product_categories/_form.html.erb
<%= form_with(model: product_category) do |form| %>
  <% if product_category.errors.any? %>
    <div class="error-messages">
      <h3><%= pluralize(product_category.errors.count, "error") %> prohibited this product from being saved:</h3>
      <ul>
        <% product_category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :sku %><br>
    <%= form.text_field :sku %>
  </div>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
  </div>

  <div>
    <%= form.submit 'Create Category'%>
  </div>
<% end %>

app/views/product_categories/edit.html.erb
<h1>Edit Category</h1>

<%= render "form", product_category: @product_category %>

app/views/product_categories/index.html.erb
<p class="notice"><%= notice %></p>

<h1>Product Categories</h1>

<table>
  <tr>
    <th>SKU</th>
    <th>name</th>
    <th>description</th>
    <th>actions</th>
  </tr>

<% @product_categories.each do |cat| %>
  <tr>
    <td><%= cat.sku %></td>
    <td><%= cat.name %></td>
    <td><%= cat.description %></td>
    <td><%= link_to 'Show', cat %>
        <%= link_to 'Edit', edit_product_category_path(cat) %>
        <%= button_to 'Delete', product_category_path(cat), method: :delete, 
        data: {  turbo_confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Category', new_product_category_path %>

app/views/product_categories/new.html.erb
<h1>New Category</h1>

<%= render "form", product_category: @product_category %>

<%= link_to 'Back to Categories', product_categories_path %>

app/views/product_categories/show.html.erb
<p class="notice"><%= notice %></p>


<h1>Category <%= @product_category.id %></h1>

<p><%= @product_category.sku %></p>
<p><%= @product_category.name %></p>
<p><%= @product_category.description %></p>

<%= link_to 'Back to Categories', product_categories_path %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div class="error-messages">
      <h3><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h3>
      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_category_id, "Category" %><br>
    <%= form.select :product_category_id, ProductCategory.all.map {|c| [c.name, c.id] } %>
  </div>

  <div>
    <%= form.label :sku %><br>
    <%= form.text_field :sku %>
  </div>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
  </div>

  <div>
    <%= form.submit 'Create Product'%>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<p class="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <tr>
    <th>Category</th>
    <th>SKU</th>
    <th>name</th>
    <th>description</th>
    <th>actions</th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.product_category.name %></td>
    <td><%= product.sku %></td>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= link_to 'Show', product %>
        <%= link_to 'Edit', edit_product_path(product) %>
        <%= button_to 'Delete', product_path(product), method: :delete, 
        data: {  turbo_confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form", product: @product %>

<%= link_to 'Back to Products', products_path %>

app/views/products/show.html.erb
<p class="notice"><%= notice %></p>


<h1>Product <%= @product.id %></h1>

<p><%= @product.product_category.name %></p>
<p><%= @product.sku %></p>
<p><%= @product.name %></p>
<p><%= @product.description %></p>

<%= link_to 'Back to Products', products_path %>

app/views/shared/_alerts.html.erb
<% if notice %>
<div class="alert alert-warning" role="alert">
  <%= notice %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <a><%= link_to 'Home', root_path, class:"nav-link" %></a>
        </li>
        <li class="nav-item">
         <a><%= link_to 'Products', products_path, class:"nav-link" %></a>
        </li>
        <li class="nav-item">
         <a><%= link_to 'Product Categories', product_categories_path, class:"nav-link" %></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>